### ISSUE TITLE
Emits strange log

### ISSUE THREAD

**Issue by udzura** [udzura/fluent-plugin-json_expander#1]
@matsumoto-r have tried my plugin, and it seems working almost OK.

But he said there are strange warnings:

```
2015-10-29 20:19:29 +0900 [warn]: parameter 'gfapi_url' in <template>
  gfapi_url http://127.0.0.1:5125/api/
  graph_path ${data[real_hostname]}/${data[hostname]}/${key_name}
  name_keys count_2xx,count_3xx,count_4xx,count_5xx
</template> is not used.
2015-10-29 20:19:29 +0900 [warn]: parameter 'graph_path' in <template>
  gfapi_url http://127.0.0.1:5125/api/
  graph_path ${data[real_hostname]}/${data[hostname]}/${key_name}
  name_keys count_2xx,count_3xx,count_4xx,count_5xx
</template> is not used.
2015-10-29 20:19:29 +0900 [warn]: parameter 'name_keys' in <template>
  gfapi_url http://127.0.0.1:5125/api/
  graph_path ${data[real_hostname]}/${data[hostname]}/${key_name}
  name_keys count_2xx,count_3xx,count_4xx,count_5xx
</template> is not used.
```

**Comment by udzura** [comment]
This kind of log is found in:
https://github.com/fluent/fluentd/blob/master/lib/fluent/engine.rb#L95

**Comment by udzura** [comment]
I have added https://github.com/udzura/fluent-plugin-json_expander/commit/0916ca4a0d247ebb89ede5ab0a7698b1fb77df3b and run `LOG2STDOUT=1 rake test`, but I didn't find this kind of errors...

**Comment by matsumotory** [comment]
Thank you for your investigation. I attached the configuration and log on gist. 

https://gist.github.com/matsumoto-r/901ab204076c9cbc947b

**Comment by udzura** [comment]
@matsumoto-r Thanks!

Is this log output ocurred in each request, or just once on boot?

```
2015-10-29 20:19:29 +0900 [warn]: parameter 'name_keys' in <template>
  gfapi_url http://127.0.0.1:5125/api/
  graph_path ${data[real_hostname]}/${data[hostname]}/${key_name}
  name_keys ucpu,scpu,memory,total_size,total_content_length
</template> is not used.
```

**Comment by matsumotory** [comment]
> Is this log output ocurred in each request, or just once on boot?

just once on boot. And, both fluentd and growthdorecast works correctly.

**Comment by udzura** [comment]
Thanks again! The seems to be a problem in parsing settings.
